package learning.Days;

import java.util.Random;
import java.util.stream.Stream;

public class Seven {

	public static void main(String[] args) {
		Random random = new Random();
		
		var employeeList = Stream.iterate(126, t -> random.nextInt(1000)).distinct().limit(10);
		
		
		employeeList.map(t -> new Employee("E" + t,random.nextLong(20000, 500000),Department.values()[random.nextInt(9)].toString(),random.nextBoolean()))
		.forEach(t -> System.out.println(t.toString()));

		
		/*
		 * 
			int i = 0;
			
			//random intstream generated by Random class
			random.ints(4,0,1000).forEach(System.out::println);
			while(i!=5) {
				System.out.println(random.nextInt(1000));
				System.out.println(random.nextLong(500000));
				System.out.println(random.nextBoolean());
				
				i++;
			}
		*
		*/
		
	}
}
